repos:
  - repo: local
    hooks:
      - id: check-filenames
        name: check-filenames
        entry: python ./scripts/check_filenames.py
        language: system
        files: '.*'

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        name: prettier (frontend)
        language: node
        files: '^frontend/.*\.(js|jsx|ts|tsx|css|scss|html|json|md)$'
        args: ['--write']
